-- Auto-generated schema dump (structure only, no data).
-- Generated by introspecting the project's Postgres database (information_schema + pg_catalog).
-- Used to provision the throwaway Postgres service in CI for integration tests.
-- If the real schema changes, regenerate this file (see backend/db/README.md).

CREATE TYPE "complexidade_projeto" AS ENUM ('baixa', 'media', 'alta');
CREATE TYPE "prioridade_requisito" AS ENUM ('baixa', 'media', 'alta', 'critica');
CREATE TYPE "nivel_usuario" AS ENUM ('USUARIO', 'MASTER', 'ADMINISTRADOR');

CREATE SEQUENCE IF NOT EXISTS "clientes_id_seq";
CREATE SEQUENCE IF NOT EXISTS "contribuidores_id_seq";
CREATE SEQUENCE IF NOT EXISTS "documentos_id_seq";
CREATE SEQUENCE IF NOT EXISTS "enderecos_id_seq";
CREATE SEQUENCE IF NOT EXISTS "logs_id_seq";
CREATE SEQUENCE IF NOT EXISTS "projetos_id_seq";
CREATE SEQUENCE IF NOT EXISTS "recursos_id_seq";
CREATE SEQUENCE IF NOT EXISTS "requisitos_id_seq";
CREATE SEQUENCE IF NOT EXISTS "tecnologias_id_seq";
CREATE SEQUENCE IF NOT EXISTS "testes_id_seq";
CREATE SEQUENCE IF NOT EXISTS "treinamentos_id_seq";
CREATE SEQUENCE IF NOT EXISTS "usuarios_id_seq";

CREATE TABLE IF NOT EXISTS "clientes" (
  "id" bigint DEFAULT nextval('clientes_id_seq'::regclass) NOT NULL,
  "razao_social" varchar(255) NOT NULL,
  "cnpj" varchar(18) NOT NULL,
  "email" varchar(255) NOT NULL,
  "telefone" varchar(20),
  "setor" varchar(100),
  "contato" varchar(255),
  "data_criacao" timestamptz DEFAULT now(),
  "endereco_id" bigint,
  PRIMARY KEY ("id"),
  UNIQUE ("cnpj")
);

CREATE TABLE IF NOT EXISTS "contribuidores" (
  "id" bigint DEFAULT nextval('contribuidores_id_seq'::regclass) NOT NULL,
  "nome" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "telefone" varchar(20),
  "cargo" varchar(100),
  "empresa" varchar(255),
  "ativo" boolean DEFAULT true,
  PRIMARY KEY ("id"),
  UNIQUE ("email")
);

CREATE TABLE IF NOT EXISTS "contribuidores_projeto" (
  "contribuidor_id" bigint NOT NULL,
  "projeto_id" bigint NOT NULL,
  "data_inicio" date NOT NULL,
  "data_fim" date,
  PRIMARY KEY ("contribuidor_id", "projeto_id")
);

CREATE TABLE IF NOT EXISTS "documentos" (
  "id" bigint DEFAULT nextval('documentos_id_seq'::regclass) NOT NULL,
  "tipo" varchar(100),
  "descricao" text,
  "arquivo_url" text NOT NULL,
  "nome_do_arquivo" varchar(255) NOT NULL,
  "data_criacao" timestamptz DEFAULT now(),
  "data_aprovacao" timestamptz,
  "projeto_id" bigint NOT NULL,
  "aprovado_por_id" bigint,
  "conteudo_json" jsonb,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "enderecos" (
  "id" bigint DEFAULT nextval('enderecos_id_seq'::regclass) NOT NULL,
  "logradouro" varchar(255) NOT NULL,
  "cep" varchar(9) NOT NULL,
  "numero" varchar(20),
  "bairro" varchar(100),
  "cidade" varchar(100) NOT NULL,
  "estado" varchar(2) NOT NULL,
  "pais" varchar(50) NOT NULL,
  "complemento" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "logs" (
  "id" bigint DEFAULT nextval('logs_id_seq'::regclass) NOT NULL,
  "nome_tabela" varchar(100) NOT NULL,
  "nome_campo" varchar(100),
  "chave_primaria_registro" varchar(255) NOT NULL,
  "chave_secundaria_registro" varchar(255),
  "tipo_acao" varchar(10) NOT NULL,
  "valor_antigo" text,
  "valor_novo" text,
  "data_hora" timestamptz DEFAULT now(),
  "modificado_por_id" bigint,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "projetos" (
  "id" bigint DEFAULT nextval('projetos_id_seq'::regclass) NOT NULL,
  "nome_projeto" varchar(255) NOT NULL,
  "descricao" text,
  "modelo_projeto" varchar(100),
  "metodologia" varchar(100),
  "escopo" text,
  "data_inicio" date,
  "data_final_previsto" date,
  "data_final" date,
  "complexidade" complexidade_projeto,
  "orcamento_estimado" numeric(18,2),
  "data_criacao" timestamptz DEFAULT now(),
  "cliente_id" bigint NOT NULL,
  "responsavel_id" bigint,
  "criado_por_id" bigint NOT NULL,
  "tipo" varchar(50) DEFAULT 'OUTROS'::character varying,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "recursos" (
  "id" bigint DEFAULT nextval('recursos_id_seq'::regclass) NOT NULL,
  "nome" varchar(255) NOT NULL,
  "tipo" varchar(100) NOT NULL,
  "disponivel" boolean DEFAULT true,
  "descricao" text,
  "data_criacao" timestamptz DEFAULT now(),
  "criado_por_id" bigint,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "recursos_projeto" (
  "recurso_id" bigint NOT NULL,
  "projeto_id" bigint NOT NULL,
  "custo_hora" numeric(10,2),
  "data_alocacao" date NOT NULL,
  "data_desalocacao" date,
  PRIMARY KEY ("recurso_id", "projeto_id")
);

CREATE TABLE IF NOT EXISTS "requisitos" (
  "id" bigint DEFAULT nextval('requisitos_id_seq'::regclass) NOT NULL,
  "tipo" varchar(100) NOT NULL,
  "descricao" text NOT NULL,
  "observacoes" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "requisitos_projeto" (
  "requisito_id" bigint NOT NULL,
  "projeto_id" bigint NOT NULL,
  "codigo_requisito" varchar(50),
  "prioridade" prioridade_requisito,
  "data_aprovacao" timestamptz,
  "aprovado_por_id" bigint,
  "criado_por_id" bigint,
  PRIMARY KEY ("requisito_id", "projeto_id"),
  UNIQUE ("codigo_requisito")
);

CREATE TABLE IF NOT EXISTS "tecnologias" (
  "id" bigint DEFAULT nextval('tecnologias_id_seq'::regclass) NOT NULL,
  "nome" varchar(255) NOT NULL,
  "categoria" varchar(100),
  "descricao" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "tecnologias_projeto" (
  "tecnologia_id" bigint NOT NULL,
  "projeto_id" bigint NOT NULL,
  "data_aprovacao" timestamptz,
  "aprovado_por_id" bigint,
  PRIMARY KEY ("tecnologia_id", "projeto_id")
);

CREATE TABLE IF NOT EXISTS "testes" (
  "id" bigint DEFAULT nextval('testes_id_seq'::regclass) NOT NULL,
  "nome" varchar(255) NOT NULL,
  "descricao" text,
  "projeto_id" bigint NOT NULL,
  "situacao" varchar(50) DEFAULT 'pendente'::character varying,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "treinamentos" (
  "id" bigint DEFAULT nextval('treinamentos_id_seq'::regclass) NOT NULL,
  "nome" varchar(255) NOT NULL,
  "descricao" text,
  "tipo_treinamento" varchar(100),
  "data_inicio" timestamptz,
  "data_termino" timestamptz,
  "duracao_horas" integer,
  "instrutor" varchar(255),
  "projeto_id" bigint NOT NULL,
  "criado_por_id" bigint,
  "documento_id" bigint,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "usuarios" (
  "id" bigint DEFAULT nextval('usuarios_id_seq'::regclass) NOT NULL,
  "nome" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "senha" text,
  "nivel" nivel_usuario NOT NULL,
  "telefone" varchar(20),
  PRIMARY KEY ("id"),
  UNIQUE ("email")
);

ALTER TABLE "clientes" ADD CONSTRAINT "clientes_endereco_id_fkey" FOREIGN KEY ("endereco_id") REFERENCES "enderecos" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "contribuidores_projeto" ADD CONSTRAINT "contribuidores_projeto_contribuidor_id_fkey" FOREIGN KEY ("contribuidor_id") REFERENCES "contribuidores" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "contribuidores_projeto" ADD CONSTRAINT "contribuidores_projeto_projeto_id_fkey" FOREIGN KEY ("projeto_id") REFERENCES "projetos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documentos" ADD CONSTRAINT "documentos_projeto_id_fkey" FOREIGN KEY ("projeto_id") REFERENCES "projetos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documentos" ADD CONSTRAINT "documentos_aprovado_por_id_fkey" FOREIGN KEY ("aprovado_por_id") REFERENCES "usuarios" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "logs" ADD CONSTRAINT "logs_modificado_por_id_fkey" FOREIGN KEY ("modificado_por_id") REFERENCES "usuarios" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "projetos" ADD CONSTRAINT "projetos_cliente_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "projetos" ADD CONSTRAINT "projetos_responsavel_id_fkey" FOREIGN KEY ("responsavel_id") REFERENCES "usuarios" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "projetos" ADD CONSTRAINT "projetos_criado_por_id_fkey" FOREIGN KEY ("criado_por_id") REFERENCES "usuarios" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "recursos" ADD CONSTRAINT "recursos_criado_por_id_fkey" FOREIGN KEY ("criado_por_id") REFERENCES "usuarios" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "recursos_projeto" ADD CONSTRAINT "recursos_projeto_recurso_id_fkey" FOREIGN KEY ("recurso_id") REFERENCES "recursos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "recursos_projeto" ADD CONSTRAINT "recursos_projeto_projeto_id_fkey" FOREIGN KEY ("projeto_id") REFERENCES "projetos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "requisitos_projeto" ADD CONSTRAINT "requisitos_projeto_requisito_id_fkey" FOREIGN KEY ("requisito_id") REFERENCES "requisitos" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "requisitos_projeto" ADD CONSTRAINT "requisitos_projeto_projeto_id_fkey" FOREIGN KEY ("projeto_id") REFERENCES "projetos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "requisitos_projeto" ADD CONSTRAINT "requisitos_projeto_aprovado_por_id_fkey" FOREIGN KEY ("aprovado_por_id") REFERENCES "usuarios" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "requisitos_projeto" ADD CONSTRAINT "requisitos_projeto_criado_por_id_fkey" FOREIGN KEY ("criado_por_id") REFERENCES "usuarios" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tecnologias_projeto" ADD CONSTRAINT "tecnologias_projeto_tecnologia_id_fkey" FOREIGN KEY ("tecnologia_id") REFERENCES "tecnologias" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tecnologias_projeto" ADD CONSTRAINT "tecnologias_projeto_projeto_id_fkey" FOREIGN KEY ("projeto_id") REFERENCES "projetos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "tecnologias_projeto" ADD CONSTRAINT "tecnologias_projeto_aprovado_por_id_fkey" FOREIGN KEY ("aprovado_por_id") REFERENCES "usuarios" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "testes" ADD CONSTRAINT "testes_projeto_id_fkey" FOREIGN KEY ("projeto_id") REFERENCES "projetos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "treinamentos" ADD CONSTRAINT "treinamentos_projeto_id_fkey" FOREIGN KEY ("projeto_id") REFERENCES "projetos" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "treinamentos" ADD CONSTRAINT "treinamentos_criado_por_id_fkey" FOREIGN KEY ("criado_por_id") REFERENCES "usuarios" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "treinamentos" ADD CONSTRAINT "treinamentos_documento_id_fkey" FOREIGN KEY ("documento_id") REFERENCES "documentos" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
